feat: Indexer detect long fork
nervosnetwork/ckb-cli pull request #345
Opened 2020-10-29 14:08 UTC by TheWaWaR

* Detect long fork from index database and log an error level message
* Rebuild current index database though sub-command

2020-11-25 09:55 UTC, quake approved these changes

2020-11-26 01:31 UTC, keroro520 requested changes

2020-11-26 01:31 UTC, keroro520 commented on src/subcommands/index.rs
> +                App::new("current-database-info")
mix-use `db` and `database`?

2020-11-26 01:31 UTC, keroro520 commented on src/subcommands/wallet/index.rs
> +                    return Ok((true, false));
Why return `Ok(exit=true, rebuild=false)` but not `Err(..)`. I think that would be better to display the above error message onto the user terminal as well.

2020-12-08 15:59 UTC, TheWaWaR commented on src/subcommands/wallet/index.rs
> +                    return Ok((true, false));
Because `Err(...)` will let the thread continue running after sleep 2 seconds. I think a error log is enough to warn the user.

2020-12-09 02:35 UTC, keroro520 commented
@TheWaWaR ci failed

2020-12-09 02:39 UTC, TheWaWaR commented
> @TheWaWaR ci failed

It’s because Travis cached a very old version of test/Cargo.lock, copy the root Cargo.lock file to test directory will fix this. The fix is in v0.39 PR.

2020-12-09 02:40 UTC, keroro520 approved these changes

2020-12-09 03:36 UTC, quake approved these changes

2020-12-09 11:56 UTC, merged