Add general rpc subscription client
nervosnetwork/ckb-cli pull request #365
Opened 2021-02-24 11:00 UTC by driftluo

2021-02-25 03:08 UTC, doitian approved these changes

2021-02-25 06:05 UTC, quake commented on ckb-sdk/src/pubsub/stream_codec.rs
> +// copy from jsonrpc service-util
Please add a link to original copy

2021-02-25 06:08 UTC, quake requested changes

2021-02-25 06:08 UTC, quake commented on src/main.rs
> +        ("pubsub", Some(sub_matches)) => {
I think this cmd should be added as a sub-cmb of `rpc`:
```
./ckb-cli rpc subscribe new_tip_header
```

2021-02-25 06:31 UTC, TheWaWaR commented on src/main.rs
> +        ("pubsub", Some(sub_matches)) => {
Because rustyline can not handle Ctrl + C nicely. So the subcommand should disabled in interactive mode. Maybe `ckb-cli rpc-subscribe new_tip_header` ?

2021-02-25 07:39 UTC, quake commented on ckb-sdk/src/pubsub/stream_codec.rs
> +/// I changed the return value of decode to BytesMut. It is not a good idea to parse it into a string in the codec.
The character encoding of JSON text is always Unicode. UTF-8 is the only encoding that makes sense on the wire, if the encoding is the only issue, I prefer using the original code as lib to copy-write this file.

2021-02-25 07:42 UTC, quake commented on ckb-sdk/src/pubsub/mod.rs
> +            r#"{{"id": 2, "jsonrpc": "2.0", "method": "subscribe", "params": ["{}"]}}"#,
according to json rpc rfcs, the "id" is returned in the corresponding response object, so user can map one response to the request, using fixed id here is not best practice

2021-02-25 13:02 UTC, driftluo commented on ckb-sdk/src/pubsub/mod.rs
> +            r#"{{"id": 2, "jsonrpc": "2.0", "method": "subscribe", "params": ["{}"]}}"#,
It is indeed necessary to do this under the premise of reusing io. At present, the io multiplexing function has been added, and id has been auto-incremented.

2021-02-26 05:28 UTC, TheWaWaR requested changes

2021-02-26 05:28 UTC, TheWaWaR commented on src/subcommands/pubsub.rs
> +            let c = new_tcp_client($addr).await.unwrap();
Please report meaningful error (return `Err(String)`) instead of panic.

2021-02-26 06:55 UTC, TheWaWaR approved these changes

2021-03-18 05:37 UTC, quake approved these changes

2021-03-18 05:50 UTC, merged