Bump ckb dependencies to v0.116.0-rc2
nervosnetwork/ckb-cli pull request #598
Opened 2024-04-27 09:32 UTC by eval-exec

2024-05-11 07:06 UTC, 15168316096 requested changes

2024-05-11 07:06 UTC, 15168316096 commented on src/utils/rpc/client.rs
> +            .get_live_cell(out_point.into(), with_data, include_tx_pool)
@eval-exec 
If you are using a ckb node below version 116.1, if you do not judge the version compatibility, you will get an error when using this interface.
{"id": 42, "jsonrpc": "2.0", "method": "get_live_cell", "params": [{"index": "0x0", "tx_hash": "0x1ed55dfc5703018d5d689e9282c79f44b3923576a8b684e6acfff50357d17a8 5"}, true, null] }
response:
{"jsonrpc": "2.0", "error": {"code": -32602, "message": "Invalid params: invalid length 3, expected fewer elements in array."}, "id": 42}
Exception: Error: Invalid params: invalid length 3, expected fewer elements in array.

2024-05-11 22:36 UTC, eval-exec commented on src/utils/rpc/client.rs
> +            .get_live_cell(out_point.into(), with_data, include_tx_pool)
ckb version 0.116.1 does not contain the code change for `get_live_cell`. I will revert the last commit.

2024-05-13 01:42 UTC, doitian approved these changes

2024-05-13 01:42 UTC, merged